#' Main internal routine for enumeration
#'
#' @param S A matrix whose columns are the elements to be covered, and whose rows are the available subsets from which to build the covers
#' @param G The adjacency matrix specifying the DAG
#' @return A list of all minimally consistent covers
#' @examples
#' mcc_enum(S,G)
.mcc_enum <- function(S, G, verbose) {  #ALGORITHM 1

  #some housekeeping first
  C <- vector("list", 1000)     #preallocate cover list with 1000 slots
  m <- 6                        #maximum community rank to consider
  b <- 1                        #counter for total number of unique communities


  #begin by getting rank-1 communities
  if (max(G)>1) {D <- .extcomrank1(S,G, verbose)}
  else          {D <- .comrank1(S,G)}


  #now look at higher ranks
  for (j in 1:m) {

    a <- 0                      #counter for number of unique communities at rank j

    if (verbose) {cat(sprintf('Community rank %i', j))}

    Tr <- .comrankj(j, D)

    TrN <- length(Tr)

    for (i in 1:TrN) {

      if (verbose) {cat(sprintf('\tConsidering %i communities', length(Tr)))}

      if (verbose) {cat(sprintf("\rCommunity rank %i\tConsidering %i of %i communities", j, i, TrN))}

      tr <- Tr[[i]]

      P <- .getelders(tr, G)

      if (.iswellformed(tr, j, G, P)) {
        if (.isdominant(tr, S, P)) {
          if (.iscover(tr, S)) {

            C[[b]] <- tr
            a      <- a + 1
            b      <- b + 1

          }
        }
      }
    }

    if (verbose) {cat(sprintf("\nAt rank %i, added %i covers\n", j, a))}
  }


  # cleanup
  C <- Filter(Negate(is.null), C)
  if (length(C)>0) {C <- unique(C)}


  # finish
  if (verbose) {cat(sprintf("\nTotal number of minimal consistent covers =  %i \n", length(C)))}
  return(C)

}





#' Internal routine to find all rank-1 communities
#'
#' @param S A matrix whose columns are the elements to be covered, and whose rows are the available subsets from which to build the covers
#' @param G The adjacency matrix specifying the DAG
#' @return A list of all rank-1 communities
#' @examples
#' comrank1(S,G)
.comrank1 <- function(S,G) {      #ALGORITHM 2

  n <- nrow(S)
  D <- vector("list", n )

  for (i in 1:n) {

    a <- .traverse(G, i)

    if (.isdominant(a, S, i)) {

      D[[i]] <- sort(a)
    }
  }

  D <- Filter(Negate(is.null), D)

  return(D)

}



#' Internal routine to find all rank-j communities, using a list of rank-1 communities as building blocks
#'
#' @param j A positive integer specifying the desired rank
#' @param D A list of rank-1 communities as generated by COMRANK1
#' @return A list of all rank-j communities
#' @examples
#' COMRANKJ(S,G)
.comrankj <- function(j, D) {    #Algorithm 3

  Tr <- list()
  comb_set <- combn(length(D),j)
  n <- dim(comb_set)[2]

  Tr <- vector("list", n)

  for (i in 1:n){

    temp <- D[comb_set[,i]]
    temp <- .Internal(unlist(temp, FALSE, FALSE))
    temp <- kit::funique(temp)        #kit::funique is a fast version of unique
    Tr[[i]] <- Rfast::Sort(temp)      #Rfast::Sort is a fast version of sort


  }

  Tr <- Filter(Negate(is.null), Tr)

  Tr <- unique(Tr)

  return(Tr)
}





#' Determines if a specified community is dominant
#'
#' @param t A community
#' @param S The subset family
#' @param P The path matrix
#' @return TRUE if t is dominant;  FALSE otherwise
#' @examples
#' ISDOMINANT(t, S, P)
.isdominant <- function(t, S, P) {   #Algorithm 4

  for (i in 1:length(P)) {

    sx <- S[P[i],]

    q <- t[-which(t==P[i])]

    if (length(q)==1)
      qx <- S[q,]
    else
      qx <- 1*(colSums(S[q,])>0)

    if (.issuperset(qx,sx)) {return (FALSE)}

  }

  return(TRUE)


}

